version: '3.8'

services:
  form-builder:
    build:
      context: . 
    container_name: form-builder
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/snapform
      - NEXTAUTH_URL=https://snapform.live
      - NEXTAUTH_SECRET=LKSMdf943nnfii43nfd3ef0ewnfnd2we9
    networks:
      - toki_toki


networks:
  toki_toki:
    external: true