version: '3.8'

services:
  form-builder:
    build:
      context: . # Make sure your Dockerfile is in this directory
    container_name: form-builder
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - toki_toki


networks:
  toki_toki:
    external: true